[styling]
# Использовать базовую подсветку
default=default

[keywords]
# Ключевые слова Typst для подсветки
primary=let set show if else for while in import include return

[settings]
extension=typ
comment_single=//
comment_open=/*
comment_close=*/

[build-menu]
# Команда компиляции в pdf (F8)
FT_00_LB=Компилировать pdf
FT_00_CM=typst compile "%f"

# Команда непрерывной сборки / отслеживания изменений (F9)
FT_01_LB=Watch (Автосборка)
# FT_01_CM=typst watch "%f"
FT_01_CM=typst watch "%d/main.typ" & WATCH_PID=$!; evince "%d/main.pdf"; kill $WATCH_PID

# Команда просмотра готового pdf (F5)
EX_00_LB=Просмотреть PDF
EX_00_CM=xdg-open "%e.pdf"
